
% Trim the data generated by run_nuclei_detection

result_map = load('result_map_3.mat');
result_map_data = result_map.result_map;

trimmed_map = trim_map(result_map_data, 3);
X = [];
Y = [];

for y = 1 : 500
    for x = 1 : 500
        if trimmed_map(y,x) == 2
            X = [X;x];
            Y = [Y;y];
        end
    end
end

RAW_IMG_DIR = './Detection';
full_img = imread([RAW_IMG_DIR '/img3/img3.bmp']);

figure, imshow(full_img);
hold on
scatter(X,Y);
hold off

function trimmed_map = trim_map(original, num)

    trimmed_map = original;
    temp = zeros(500,500);

    while num > 0
        for y = 2 : 499
            for x = 2 : 499
                if sum(sum(trimmed_map(y-1:y+1,x-1:x+1))) == 18
                    temp(y,x) = 2;
                else
                    temp(y,x) = 0;
                end
            end
        end
        trimmed_map = temp;
        temp = zeros(500,500);
        num = num - 1;
    end
end